config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  # post '/users/login/', to: 'users#login'
  
  # get "auth/:provider/callback", to: "sessions#googleAuth"
  # get "auth/failure", to: redirect("/")
  get '/comments/:id', to: 'comments#show'
  post '/comments/:id', to: 'comments#create'
  post '/tweets/:id', to: 'comments#create'
  get "users/:username", to: "users#show"
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth' }
  end

app/models/tweet.rb
class Tweet < ApplicationRecord
  def change
    add_column :title, :url, :text
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    signin_apikey
    if params[:orderby] != nil
      if params[:orderby] == "newest"
        @tweets = Tweet.all.order("created_at DESC")
      elsif params[:orderby] == "past"
        @tweets = Tweet.all.order("created_at ASC")
      elsif params[:orderby] == "ask"
        @tweets = Tweet.where({ ask: true })
      elsif params[:orderby] == "url"
        @tweets = Tweet.where({ ask: false })
      else 
        @tweets = Tweet.all
      end
    else
      if params[:user_id] != nil
        if params[:voted] == "true"
          puts params[:user_id]
          puts session[:user_id]
          if params[:user_id] == session[:user_id].to_s
            puts "entro a dins if user_id=session_id"
            @tweets = []
            @liked = Vote.where(idUser: params[:user_id], tipus: "contribution")
            @liked.each do |vote|
              @tweet =Tweet.where(id: vote.idType)
              if @tweet != nil
                @tweets.push(@tweet)
              end
            end
          else
            puts "entro else"
            msg = "You can't look at the contributions voted by another user"
            respond_to do |format|
              format.html { redirect_to '/tweets' }
              format.json { render json: msg.to_json , status: 403, location: @tweet }
              end
            return
          end
        else
          @author = User.find(params[:user_id])
          @tweets = Tweet.where(author: @author.username)
        end
      else
        @tweets = Tweet.all
      end
    end
    render :json => @tweets.to_json
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    signin_apikey
    
    if params[:vote] != nil
      if session[:user_id] != nil
        @userID = User.find(session[:user_id]).id
        if @tweet.user_id == @userID
          msg = "You can't vote your contribution"
          if params[:show] == nil
            respond_to do |format|
              format.html { redirect_to '/tweets' }
              format.json { render json: msg.to_json , status: 403, location: @tweet }
            end
          end
        else
          if params[:vote] == "true"
            @vote = Vote.find_by(tipus: "contribution", idType: params[:id], idUser: @userID)
            if @vote != nil
                if params[:show] == nil
                msg = "You have alredy voted this contribution"
                respond_to do |format|
                  format.html { redirect_to '/tweets' }
                  format.json { render json: msg.to_json , status: 400, location: @tweet }
                  end
              end
            else
              @vote = Vote.new
              @vote.tipus = "contribution"
              @vote.idType = params[:id]
              @vote.idUser = @userID
              @vote.save
              @tweet.points += 1
              @tweet.save
              @user = User.find(@tweet.user_id)
              @user.karma += 3
              @user.save
              if params[:show] == nil
              msg = "The contribution has been voted"
              respond_to do |format|
                format.html { redirect_to '/tweets' }
                format.json { render json: @tweet.to_json , status: 200, location: @tweet }
                end
              end
            end
          elsif params[:vote] == "false"
            @vote = Vote.find_by(tipus: "contribution", idType: params[:id], idUser: @userID)
            if @vote.nil?
              if params[:show] == nil
              msg = "You have alredy unvoted this contribution"
              respond_to do |format|
              format.html { redirect_to '/tweets' }
              format.json { render json: msg.to_json , status: 400, location: @tweet }
              end
            end
            else
              @vote.destroy
              @tweet.points -= 1
              @tweet.save
              @user = User.find(@tweet.user_id)
              @user.karma -= 3
              @user.save
              if params[:show] == nil
              msg = "The contribution has been unvoted"
              respond_to do |format|
                format.html { redirect_to '/tweets' }
                format.json { render json: @tweet.to_json , status: 200, location: @tweet }
                end
              end
            end
          end
        end
      else
        msg = "You don't have a valid api_key"
        respond_to do |format|
          format.json { render json: {message: msg }, status: 401 }
        end
      end
    else
      render :json => @tweet.attributes.merge( )
    end
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    signin_apikey
    
    if session[:user_id] != nil
      @tweet = Tweet.new(tweet_params)
      @tweet.author = User.find(session[:user_id]).email.split('@')[0].strip
      @tweet.user_id = User.find(session[:user_id]).id
      if !@tweet.url.blank?
        if !is_url(@tweet.url)
          respond_to do |format|
            format.json { render json: "Invalid url!".to_json, status: 400 }
          end
          return
        end
        @tweet.url = @tweet.url.sub "https://", ""
        @tweet.url = @tweet.url.sub "www.", ""
        @urlsplit = @tweet.url.split("/")
          @urlsplit.each do |suburl|
            if suburl.include?(".")
              @tweet.shorturl = suburl
            end
          end
      end
      @tweet2 = Tweet.find_by url: @tweet.url
      if (@tweet.content.blank? && !@tweet.url.blank?)
        respond_to do |format|
          if @tweet.title.blank?
            format.html { redirect_to new_tweet_path, alert: 'Please try again.' }
            format.json { render json: "Title property cannot be blank".to_json, status: 400 }
          elsif (@tweet2 != nil)
            format.html { redirect_to '/tweets/' + @tweet2.id.to_s }
            msg = "The URL already exists"
            format.json { render json: msg.to_json , status: 400, location: @tweet }
          elsif @tweet.save
              format.html { redirect_to '/tweets', notice: 'Tweet was successfully created.' }
              format.json { render json: @tweet, status: 201 }
          else
            format.html { render :new }
            format.json { render json: @tweet.errors, status: :unprocessable_entity }
          end
        end
      elsif (@tweet.url.blank? && !@tweet.content.blank?)
        @tweet.ask = true
        respond_to do |format|
          if @tweet.title.blank?
            format.html { redirect_to new_tweet_path, alert: 'Please try again.' }
            format.json { render json: "Title property cannot be blank".to_json, status: 400 }
          elsif @tweet.save
              format.html { redirect_to '/tweets', notice: 'Tweet was successfully created.' }
              format.json { render json: @tweet, status: 201 }
          else
            format.html { render :new }
            format.json { render json: @tweet.errors, status: :unprocessable_entity }
          end
        end
      else
        @comment_text=@tweet.content
        @tweet.content=nil
        @tweet.ask = false
        
        if @tweet.save
          Comment.create(contribution: @tweet.id, text: @comment_text, escomment: true, comment_id: nil, user: @tweet.user_id)
          render :json => @tweet.attributes.merge( )
        end
      end
    else
      respond_to do |format|
        format.json { render json: {message: 'Unauthorized, you don\'t have a valid api_key' }, status: 401 }
       end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    signin_apikey
    if session[:user_id] != nil
      if @tweet.user_id.to_s == session[:user_id].to_s
        respond_to do |format|
          if @tweet.update(tweet_update_params)
            format.html { redirect_to @tweet, notice: 'Tweet was successfully edited.' }
            format.json { render json: @tweet, status: 200 }
          else
            format.html { render :edit }
            format.json { render json: @tweet.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
        format.json { render json: {message: 'Forbidden, you can\'t edit a tweet that is not yours' }, status: 403 }
       end
     end
    else
      respond_to do |format|
        format.json { render json: {message: 'Unauthorized, you don\'t have a valid api_key' }, status: 401 }
       end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    signin_apikey
    if session[:user_id] != nil
      if @tweet.user_id.to_s == session[:user_id].to_s
        @tweet.destroy
        respond_to do |format|
          format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
          format.json { render json: {message: 'Contribution destroyed!' } }
        end
      else
        respond_to do |format|
        format.json { render json: {message: 'Forbidden, you can\'t delete a tweet that is not yours' }, status: 403 }
       end
      end
    else
      respond_to do |format|
        format.json { render json: {message: 'Unauthorized, you don\'t have a valid api_key' }, status: 401 }
       end
    end
  end

  private
  
    def signin_apikey
      if request.headers["X-API-KEY"] != nil
        puts "Header:"
        puts request.headers["X-API-KEY"]
        @user = User.where(api_key: request.headers["X-API-KEY"]).take
        session[:user_id] = @user.id
      end
    end
    
    def is_url(url)
      @a = false
      if (url.include?("www") || url.include?("http"))
        @a=true
      end
      return @a
    end
      
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= stylesheet_link_tag "application" %>
<div id="background">
<div id ="header">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/tweets"><img src="https://news.ycombinator.com/favicon.ico" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a>Submit</a></b>
                  </span></td>
              </tr></table></td>
              </tr></div>
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  
  <div class="field">
    <%= form.label :url %>
    <%= form.text_area :url %>
  </div>
  
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.hidden_field :author, :value=> session[:user_id]%> 
  </div>

  <div class="actions">
    <%= form.submit :Submit %>
  </div>
  
  <p>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.</p>
  <p>You can also submit via bookmarklet.</p>
<% end %>
</div>

app/views/tweets/_form3.html.erb
<form class="profileform" method="post" action="/tweets/<%= @tweet.id %>">
   <input name="_method" type="hidden" value="patch" />
   <table>
  <tbody>
        <tr>
            <td><strong>Title:</strong></td>
            <td>
                  <textarea cols="20" rows="2" wrap="virtual" name="title"><%= @tweet.title %></textarea>
            </td>
        </tr>
        <tr>
        <% if @tweet.ask == true %> 
            <td><strong>Content:</strong></td>
            <td>
                  <textarea cols="60" rows="5" wrap="virtual" name="content"><%= @tweet.content %></textarea>
            </td>
        <% else %> 
            <td><strong>Url:</strong></td>
            <td>
                  <p cols="60" rows="5" wrap="virtual" name="url"><%= @tweet.url %></p>
            </td>
        <% end %>
        </tr>
        <tr>
            <td> 
                <div class="actions">
                    <input type="submit" value="update" />
                </div>
            </td>
        </tr>
     
    
  </tbody>
  </table>
  </form>

app/views/tweets/edit.html.erb
<div id="background">
<div id ="header">
    <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/tweets"><img src="https://news.ycombinator.com/favicon.ico" width="18" height="18" style="border:1px white solid;"></a></td>
                    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/tweets">Hacker News</a></b>
                <a href="/tweets?orderby=newest">new</a><%if session[:user_id]!= nil %> | threads <%end%>| <a href="/tweets?orderby=past">past</a> | <a href="/comments">comments</a> | <a href="/tweets?orderby=ask">ask</a> | <a href="/tweets?orderby=url">show</a> | jobs <%if session[:user_id] != nil %>|<%= link_to 'Submit', new_tweet_path %><%else %>| <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to "Submit", omniauth_authorize_path(resource_name, provider), method: :post %> <%end%>  <% end %>      </span></td>
                        <td style="text-align:right;padding-right:4px;"><span class="pagetop">
                                
                              <% if session[:user_id] == nil %>
                                <%- if devise_mapping.omniauthable? %>
                                  <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to "Login", omniauth_authorize_path(resource_name, provider), method: :post %><br />
                                  <% end -%>
                                <% end -%>
                              <% else %>
                                    <% @username = User.find(session[:user_id]).email.split('@')[0].strip %>
                                   <p><%= @username %>(<%=User.find(session[:user_id]).karma%>) | 
                                   <a href="/users/<%= session[:user_id] %>?logout=true">logout</a></p>
                              <%end%>
                  
                            </span></td>
                </tr></table></td>
                </tr>
  </div>
  
<table>

  <tbody>
      <tr>
        <td> 
              <% if  session[:user_id] == nil %>
                <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to image_tag('https://news.ycombinator.com/grayarrow.gif'), omniauth_authorize_path(resource_name, provider), method: :post %><br />
                  <% end -%>
              <% elsif @username != @tweet.author%> 
                <% if Vote.where(tipus: "contribution", idType: @tweet.id, idUser: User.find(session[:user_id]).id).count == 0%>
                  <a href='/tweets/<%= @tweet.id %>?vote=true'><img src="https://news.ycombinator.com/grayarrow.gif"></a> 
                <%end%>
              <%else%> 
                <p style="color: orange;">*</p>
              <%end%>
            </td>
        <td><% if @tweet.ask == false %><a href="http://<%= @tweet.url %>" target="_blank"><%= @tweet.title %></a> <%else%><a href="/tweets/<%= @tweet.id%>"><%= @tweet.title %></a> <% end %> <% if @tweet.ask == false %>(<%= @tweet.shorturl %>)<% end %></td>
      </tr>
      <tr>
        <td></td>
         <% @user = User.find(@tweet.user_id) %>
        <td class="below-info"><%= @tweet.points %> points by <% if (session[:user_id] != nil && User.find(session[:user_id]).username != @tweet.author)  || session[:user_id] == nil %> <a href="/users/<%= @user.id %>"><%= @tweet.author%></a> <% else %> <a href="/users/<%= @user.id %>/edit"><%= @tweet.author%></a> <%end%><%= time_ago_in_words(@tweet.created_at) %> ago <% if session[:user_id] != nil && Vote.where(tipus: "contribution", idType: @tweet.id, idUser: User.find(session[:user_id]).id).count == 1 %>
                  | <a href="/tweets/<%= @tweet.id %>?vote=false">unvote</a>
                  <% end %> | hide | past | <a href="/tweets/<%= @tweet.id%>"><% @num_comments = Comment.where(contribution: @tweet.id).count %> <% if @num_comments == 0 %> discuss <% else %> <%= @num_comments %> comments <% end %> </a>  <% if @username == @tweet.author%> | <%= link_to 'Edit', edit_tweet_path(@tweet) %> | <%= link_to 'Destroy', @tweet, method: :delete, data: { confirm: 'Are you sure?' } %> <%end%></td>
      </tr>
  </tbody>
</table>

<%= render 'form3', tweet: @tweet %>

<tr><td><img src="https://news.ycombinator.com/s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="https://news.ycombinator.com/newsguidelines.html">Guidelines</a>
        | <a href="https://news.ycombinator.com/newsfaq.html">FAQ</a>
        | <a href="https://news.ycombinator.com/lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="https://news.ycombinator.com/security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body>
</div>

app/views/tweets/index.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application" %>
<link rel="shortcut icon" href="favicon.ico">


<div id="background">
  <div id ="header">
    <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/tweets"><img src="https://news.ycombinator.com/favicon.ico" width="18" height="18" style="border:1px white solid;"></a></td>
                    <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/tweets">Hacker News</a></b>
                <a href="/tweets?orderby=newest">new</a><%if session[:user_id]!= nil %> | threads <%end%>| <a href="/tweets?orderby=past">past</a> | <a href="/comments">comments</a> | <a href="/tweets?orderby=ask">ask</a> | <a href="/tweets?orderby=url">show</a> | jobs <%if session[:user_id] != nil %>|<%= link_to 'Submit', new_tweet_path %><%else %>| <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to "Submit", omniauth_authorize_path(resource_name, provider), method: :post %> <%end%>  <% end %>      </span></td>
                        <td style="text-align:right;padding-right:4px;"><span class="pagetop">
                                
                              <% if session[:user_id] == nil %>
                                <%- if devise_mapping.omniauthable? %>
                                  <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to "Login", omniauth_authorize_path(resource_name, provider), method: :post %><br />
                                  <% end -%>
                                <% end -%>
                              <% else %>
                                    <% @username = User.find(session[:user_id]).email.split('@')[0].strip %>
                                   <p><a href="/users/<%= session[:user_id] %>/edit"><%= @username %>(<%=User.find(session[:user_id]).karma%>)</a> | 
                                   <a href="/users/<%= session[:user_id] %>?logout=true">logout</a></p>
                              <%end%>
                  
                            </span></td>
                </tr></table></td>
                </tr>
  </div>
<table>

  <tbody>
    <% @i=1 %>
    <% @tweets.each do |tweet| %>
    
      <tr>
        <td><%= @i %>.</td>
        <td> 
              <% if  session[:user_id] == nil %>
                <%- resource_class.omniauth_providers.each do |provider| %>
                                    <%= link_to image_tag('https://news.ycombinator.com/grayarrow.gif'), omniauth_authorize_path(resource_name, provider), method: :post %><br />
                  <% end -%>
              <% elsif @username != tweet.author%> 
                <% if Vote.where(tipus: "contribution", idType: tweet.id, idUser: User.find(session[:user_id]).id).count == 0%>
                  <a href='/tweets/<%= tweet.id %>?vote=true'><img src="https://news.ycombinator.com/grayarrow.gif"></a> 
                <%end%>
              <%else%> 
                <p style="color: orange;">*</p>
              <%end%>
            </td>
        <td><% if tweet.ask == false %><a href="http://<%= tweet.url %>" target="_blank"><%= tweet.title %></a> <%else%><a href="/tweets/<%= tweet.id%>"><%= tweet.title %></a> <% end %> <% if tweet.ask == false %>(<%= tweet.shorturl %>)<% end %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
         <% @user = User.find(tweet.user_id) %>
        <td class="below-info"><%= tweet.points %> points by <% if (session[:user_id] != nil && User.find(session[:user_id]).username != tweet.author)  || session[:user_id] == nil %> <a href="/users/<%= @user.id %>"><%=tweet.author%></a> <% else %> <a href="/users/<%= @user.id %>/edit"><%=tweet.author%></a> <%end%><%= time_ago_in_words(tweet.created_at) %> ago <% if session[:user_id] != nil && Vote.where(tipus: "contribution", idType: tweet.id, idUser: User.find(session[:user_id]).id).count == 1 %>
                  | <a href="/tweets/<%= tweet.id %>?vote=false">unvote</a>
                  <% end %> | hide | past | <a href="/tweets/<%= tweet.id%>"><% @num_comments = Comment.where(contribution: tweet.id).count %> <% if @num_comments == 0 %> discuss <% else %> <%= @num_comments %> comments <% end %> </a>  <% if @username == tweet.author%> | <%= link_to 'Edit', edit_tweet_path(tweet) %> | <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %> <%end%></td>
      </tr>
      <% @i = @i + 1 %>
    <% end %>
  </tbody>
</table>

<br>

<tr><td><img src="https://news.ycombinator.com/s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="https://news.ycombinator.com/newsguidelines.html">Guidelines</a>
        | <a href="https://news.ycombinator.com/newsfaq.html">FAQ</a>
        | <a href="https://news.ycombinator.com/lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="https://news.ycombinator.com/security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body>

</div>

app/views/tweets/new.html.erb
<%= render 'form', tweet: @tweet %>