config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :tweets
  resources :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'
  # post '/users/login/', to: 'users#login'
  
  # get "auth/:provider/callback", to: "sessions#googleAuth"
  # get "auth/failure", to: redirect("/")
  get '/comments/:id', to: 'comments#show'
  post '/comments/:id', to: 'comments#create'
  post '/tweets/:id', to: 'comments#create'
  get "users/:username", to: "users#show"
  
  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth' }
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable,
        :confirmable, :lockable, :timeoutable, 
        :omniauthable, omniauth_providers: [:google_oauth2]

  def self.create_from_google_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.username = provider_data.info.email.split('@')[0].strip
      user.skip_confirmation!
    end
  end
end

app/controllers/users/omniauth_controller.rb
class Users::OmniauthController < ApplicationController
  def google_oauth2
    @user = User.create_from_google_data(request.env['omniauth.auth'])
    @user.api_key = Digest::MD5.hexdigest @user.email
    @user.save
    if @user.persisted?
      sign_in_and_redirect @user
      session[:user_id] = @user.id
      # set_flash_message(:notice, :success, kind: 'Google') if is_navigational_format?
    else
      flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
      redirect_to new_user_registration_url
    end 
  end
  
  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
    redirect_to new_user_registration_url
  end
  
  def logout
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  

  # GET /users
  # GET /users.json
  def index
    if params[:id] != nil
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    signin_apikey
    if params[:logout] != nil
      session.clear
      respond_to do |format|
        format.html { redirect_to '/tweets'}
      end
    else
     @user = User.find(params[:id])
      if request.headers["accept"] == "application/json" or request.path.include? ".json"
        render :json => @user.attributes.merge( )
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    signin_apikey
    @user = User.new(user_params)
   
    respond_to do |format|
      if @user.save
        format.html { redirect_to tweets_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def login
    @user = User.new(user_params)
    users = User.all
    for u in users
      if @user.username == u.username
        if @user.password == u.password
          respond_to do |format|
            format.html { redirect_to tweets_url, notice: 'User was successfully logged in.' }
            format.json { render :show, status: :logged_in, location: @user }
          end
        else
          respond_to do |format|
            format.html { redirect_to new_user_path, notice: 'Incorrect password' }
            format.json { render json: @user.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    signin_apikey
    if session[:user_id]!= nil
      @user = User.find(params[:id])
      if (session[:user_id].to_s == params[:id].to_s)
        @user.update(user_params)
        respond_to do |format|
          format.html { redirect_to edit_user_path(@user) }
          format.json { render json: @user.to_json, status: 200 }
        end
      else
        respond_to do |format|
          format.json { render json: "Forbidden, you can\'t edit this user as the api_key does not match".to_json, status: 403 }
        end
      end
    else
      respond_to do |format|
          format.json { render json: "Unauthorized, you don\'t have a valid api_key".to_json, status: 401 }
        end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    signin_apikey
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      # @user = User.find(params[:id])
    end
    
    def signin_apikey
      if request.headers["X-API-KEY"] != nil
        puts "Header:"
        puts request.headers["X-API-KEY"]
        @user = User.where(api_key: request.headers["X-API-KEY"]).take
        if @user != nil
         session[:user_id] = @user.id
        end
      end
    end
    
    # Only allow a list of trusted parameters through.
    def user_params
      params.permit(:about, :email, :id, :username, :password)
    end
end

app/helpers/users/omniauth_helper.rb
module Users::OmniauthHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<form class="profileform" method="post" action="/users/<%= @user.id %>">
   <input name="_method" type="hidden" value="patch" />
   <table>
  <tbody>
      <tr>
        <td><strong>user:</strong></td>
        <td><%= @user.username %></td>
      </tr>
      
      <tr>
        <td><strong>created:</strong></td>
        <td><%= @user.created_at %></td>
      </tr>
      
      <tr>
        <td><strong>karma:</strong></td>
        <td><%= @user.karma %></td>
      </tr>
      <tr>
        <td><strong>api key:</strong></td>
        <td><%=@user.api_key%></td>
        
        
        
      </tr>
      <tr>
        <td><strong>about:</strong></td>
        <td>
              <textarea cols="60" rows="5" wrap="virtual" name="about"><%= @user.about %></textarea>
              <font size="-2"><a href="/formatdoc"><font color="#afafaf">help</font></a>
              </font>
        </td>
        
      </tr>
      <tr>
        <td></td>
        <td><%= link_to 'favorites', users_path %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to 'comments', users_path %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to 'submissions', edit_user_path(@user) %><td>
      </tr>
      <tr>
        <td> <div class="actions">
          <input type="submit" value="update" />
      </div></td>
      </tr>
     
    
  </tbody>
  </table>
  </form>

app/views/users/edit.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application" %>
<link rel="shortcut icon" href="favicon.ico">


<div id="background">
  
<div id ="header">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/tweets"><img src="https://news.ycombinator.com/favicon.ico" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/tweets">Hacker News</a></b>
              <a href="/tweets?orderby=newest">new</a><%if session[:user_id]!= nil %> | threads <%end%>| <a href="/tweets?orderby=past">past</a>| <a href="/comments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | jobs <%if session[:user_id] != nil %>|<%= link_to 'Submit', new_tweet_path %><%else %>| <%- resource_class.omniauth_providers.each do |provider| %>
                                  <%= link_to "Submit", omniauth_authorize_path(resource_name, provider), method: :post %> <%end%>  <% end %>      </span></td>
                      <td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              
                            <% if session[:user_id] == nil %>
                              <%- if devise_mapping.omniauthable? %>
                                <%- resource_class.omniauth_providers.each do |provider| %>
                                  <%= link_to "Login", omniauth_authorize_path(resource_name, provider), method: :post %><br />
                                <% end -%>
                              <% end -%>
                            <% else %>
                                  <% @username = User.find(session[:user_id]).email.split('@')[0].strip %>
                                 <p><a href="/users/<%= session[:user_id] %>/edit"><%= @username %>(<%=User.find(session[:user_id]).karma%>)</a> | 
                                 <a href="/users/<%= session[:user_id] %>?logout=true">logout</a></p>
                            <%end%>
                
                          </span></td>
              </tr></table></td>
              </tr>
</div>

<%= render 'form', user: @user %>

<br>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application" %>
<link rel="shortcut icon" href="favicon.ico">


<div id="background">
<div id ="header">
  <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="/tweets"><img src="https://news.ycombinator.com/favicon.ico" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="/tweets">Hacker News</a></b>
              <a href="/tweets?orderby=newest">new</a><%if session[:user_id]!= nil %> | threads <%end%>| <a href="/tweets?orderby=past">past</a>| <a href="/comments">comments</a> | <a href="/tweets?orderby=ask">ask</a> | <a href="/tweets?orderby=url">show</a> | jobs <%if session[:user_id] != nil %>|<%= link_to 'Submit', new_tweet_path %><%else %>| <%- resource_class.omniauth_providers.each do |provider| %>
                                  <%= link_to "Submit", omniauth_authorize_path(resource_name, provider), method: :post %> <%end%>  <% end %>      </span></td>
                      <td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              
                            <% if session[:user_id] == nil %>
                              <%- if devise_mapping.omniauthable? %>
                                <%- resource_class.omniauth_providers.each do |provider| %>
                                  <%= link_to "Login", omniauth_authorize_path(resource_name, provider), method: :post %><br />
                                <% end -%>
                              <% end -%>
                            <% else %>
                                  <% @username = User.find(session[:user_id]).email.split('@')[0].strip %>
                                 <p><a href="/users/<%= session[:user_id] %>/edit"><%= @username %>(<%=User.find(session[:user_id]).karma%>)</a> | 
                                 <a href="/users/<%= session[:user_id] %>?logout=true">logout</a></p>
                            <%end%>
                
                          </span></td>
              </tr></table></td>
              </tr>
</div>
<table>

  <tbody>
      <tr>
        <td><strong>user:</strong></td>
        <td><%= @user.username %></td>
      </tr>
      
      <tr>
        <td><strong>created:</strong></td>
        <td><%= @user.created_at %></td>
      </tr>
      
      <tr>
        <td><strong>karma:</strong></td>
        <td><%= @user.karma %></td>
      </tr>
      <tr>
        <td><strong>about:</strong></td>
        <td><%=@user.about%></td>
        
        
        
      </tr>
      <tr>
        <td></td>
        <td>favorites</td>
      </tr>
      <tr>
        <td></td>
        <td>coments</td>
      </tr>
      <tr>
        <td></td>
        <td>submissions<td>
      </tr>
      
      
    
  </tbody>
</table>

<br>

</div>